# DeepLearning 基础
- 完成一个sigmoid函数

In [1]:
# 引入math模块的exp方法来计算e的指数
import math

In [2]:
# sigmoid函数math库实现
def basic_sigmoid(x):
    return 1/(1+math.exp(-x))

In [3]:
basic_sigmoid(3)

0.9525741268224334

In [4]:
# 由于在科学计算中一般输入的都是矩阵和变量，所以实现sigmoid推荐使用numpy
import numpy as np

In [5]:
# np.exp(x)执行的操作是对输入的矩阵中的每个元素都执行e的指数运算;
x=np.array([1,2,3,4])
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [6]:
# using numpy implement sigmoid function
def np_sigmoid(x):
    return 1/(1+np.exp(-x))

In [7]:
np_sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413, 0.98201379])

In [8]:
# 上面的结果你可能会好奇为什么np函数外的操作也作用到了每一个向量中的每个元素上，其实是因为python中对一个向量的操作会返回一个与该向量相同
# 大小的向量
np.exp(-x)+1

array([1.36787944, 1.13533528, 1.04978707, 1.01831564])

- 实现sigmoid函数的导数的函数

In [9]:
def sigmoid_derivative(x):
    s=np_sigmoid(x)
    return s*(1-s)

In [10]:
sigmoid_derivative(x)

array([0.19661193, 0.10499359, 0.04517666, 0.01766271])

- 实现将图片的3D数组转换为一个向量

In [11]:
x.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [12]:
x.shape

(4,)

In [13]:
# 可以通过索引获取每个维度
x.shape[0]

4

In [14]:
# 将图片的向量（length，height，3）转换为（height×length×3,1）
def image2vector(image):
    return image.reshape(image.shape[0]*image.shape[1]*image.shape[2],1)
    

In [15]:
# image example
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

In [16]:
image.shape

(3, 3, 2)

In [17]:
image2vector(image)

array([[0.67826139],
       [0.29380381],
       [0.90714982],
       [0.52835647],
       [0.4215251 ],
       [0.45017551],
       [0.92814219],
       [0.96677647],
       [0.85304703],
       [0.52351845],
       [0.19981397],
       [0.27417313],
       [0.60659855],
       [0.00533165],
       [0.10820313],
       [0.49978937],
       [0.34144279],
       [0.94630077]])

- 规范化 使用此公式来规范化$$x=\frac{x}{||x||}$$

In [18]:
x=np.array([[0,3,4],[2,6,4]])
x

array([[0, 3, 4],
       [2, 6, 4]])

In [19]:
x.shape

(2, 3)

In [20]:
print(x)

[[0 3 4]
 [2 6 4]]


In [21]:
# 计算 ||x||
x_norm=np.linalg.norm(x,axis=1,keepdims=True)
x_norm

array([[5.        ],
       [7.48331477]])

In [22]:
# 规范化后的矩阵
x_normalized=x/x_norm
x_normalized

array([[0.        , 0.6       , 0.8       ],
       [0.26726124, 0.80178373, 0.53452248]])

- 编写规范化行的函数

In [23]:
def normalizeRows(x):
    x_norm=np.linalg.norm(x,axis=1,keepdims=True)
    return x/x_norm

In [24]:
x

array([[0, 3, 4],
       [2, 6, 4]])

In [25]:
normalizeRows(x)

array([[0.        , 0.6       , 0.8       ],
       [0.26726124, 0.80178373, 0.53452248]])

# 向量化
- 向量化后的计算效率远高于for循环

In [26]:
import time
x1=[9,2,5,0,0,7,5,0,0,0,9,2,5,0,0]
x2=[9,2,2,9,0,9,2,5,0,0,9,2,5,0,0]
tic=time.time()
dot=np.dot(x1,x2)
toc=time.time()
print(dot,'所用时间:',(toc-tic)*1000)

278 所用时间: 0.13303756713867188


In [27]:
tic=time.time()
outer=np.outer(x1,x2)
toc=time.time()
print(outer,'所用时间：',(toc-tic)*1000)

[[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]] 所用时间： 0.2288818359375


# 实现损失函数L1和L2
$$L1(\hat{y},y)=\sum_{i=0}^m|y^{(i)}-\hat{y}^{(i)}|$$
$$L2(\hat{y},y)=\sum_{i=0}^m(y^{(i)}-\hat{y}^{(i)})^2$$

In [28]:
def L1(yhat,y):
    return np.sum(np.abs(y-yhat))

In [29]:
yhat=np.array([.9,.2,.1,.4,.9])
y=np.array([1,0,0,1,1])
yhat

array([0.9, 0.2, 0.1, 0.4, 0.9])

In [30]:
L1(yhat,y)

1.1

In [31]:
def L2(yhat,y):
    return np.sum((y-yhat)**2)

In [32]:
L2(yhat,y)

0.43